### PR TITLE
Security fix: Update rake dependency

### PR DESCRIPTION
**Pull request by lagr**
Dependabot failed to create this PR so I did.

### CODE REVIEW

**Review by timoschilling — APPROVED** [review]
@lagr merge

**Comment by unimatrixZxero** [comment]
We might not even have dependabot active for this repo. I dont' see any PRs from it.

**Review by unimatrixZxero — APPROVED** [review]
@larsabot merge

**Comment by lagr** [comment]
@unimatrixZxero  Since it has been acquired, Dependabot handles the automated security fixes:

image

**Comment by unimatrixZxero** [comment]
Never mind it's on. Just checked.

**Pull request merged**
